[main]
sparse = false

[format]
group_prefix = "[{group}]"
indent = "  "
branch_marker = "*"

[colors]
default = "#FF3333"
other = "#FBBF24"
active_star = "#b7ff32"

[groups]
# STABLE
backup   = "#64748B"
default  = "#1E293B"

# DEVELOPMENT
feat     = "#10B981"
refactor = "#34D399"

# CRITICAL
fix      = "#EF4444"
hotfix   = "#DC2626"

# INFRASTRUCTURE
build    = "#3B82F6"
ci       = "#22D3EE"
release  = "#0EA5E9"

# DOCUMENTATION & TESTS
docs     = "#818CF8"
test     = "#C084FC"

# UTILITY
chore    = "#9CA3AF"

# LEGACY & EXPERIMENTS
old      = "#F59E0B"
exp      = "#F97316"
